---
- hosts: localhost
  become: true
  tasks:
    - name: Install Necessary Packages from apt
      apt:
        name: "{{item}}"
      with_items:
        - mysql-workbench 
        - redis-server
        - openjdk-8-jdk
    
    - name: Download Google Chrome deb
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: ./google-chrome-stable_current_amd64.deb
    - name: Install Google Chrome
      apt:
        deb: ./google-chrome-stable_current_amd64.deb  
  vars:
   - sublimetext_build:  3143
   - docker-compose_version: 1.19.0

  roles:
    - geerlingguy.mysql
    - dpalomar.sts
    - cmprescott.chrome
    - geerlingguy.docker
    - Stouts.mongodb
#    - softasap.sa-neo4j
    - jdauphant.sublimetext
#    - cmprescott.chrome
    - gantsign.maven
    - gantsign.atom
