---
- hosts: localhost
  become: true
  tasks:
    - name: Install Necessary Packages from apt
      apt:
        name: "{{item}}"
      with_items:
#        - mysql-workbench 
#        - redis-server
        - openjdk-8-jdk
    
    - name: Download Google Chrome deb
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: ./google-chrome-stable_current_amd64.deb
    - name: Install Google Chrome
      apt:
        deb: ./google-chrome-stable_current_amd64.deb  
  roles:
#    - geerlingguy.mysql
    - dpalomar.sts
#    - geerlingguy.docker
#    - franklinkim.mongodb
#    - softasap.sa-neo4j
    - jdauphant.sublimetext
#    - cmprescott.chrome
    - gantsign.maven